name: CI

on:
  push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]

# When a new revision is pushed to a PR, cancel all in-progress CI runs for that
# PR. See https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  checks: write

jobs:
  build-wasm:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Prepare the toolchain
      working-directory: wasm-lib
      run: ./prepare-ci.sh

    - name: Build SQLite
      working-directory: wasm-lib
      run: ./build.sh

    - uses: actions/upload-artifact@v4
      with:
        name: libsqlite3-wasm
        path: wasm-lib/libsqlite3.wasm

  build:
    needs: build-wasm
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        java-version: [11] # 17, 21

    steps:
    - uses: actions/checkout@v5

    - name: Set up Java
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '${{ matrix.java-version }}'
        cache: maven

    - uses: actions/download-artifact@v5
      with:
        name: libsqlite3-wasm

    - name: Test sqlite-jdbc-wasm
      run: mvn -B clean install

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v5
      if: success() || failure() # always run even if the previous step fails
      with:
        report_paths: '**/target/surefire-reports/TEST-*.xml'
